version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: thuduc-unlocked
    ports:
      - "5050:3000"
    restart: unless-stopped
    environment:
      - NODE_ENV=production 